
#install.packages('terra', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('rematch2', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('proxy', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('sf', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('classInt', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('s2', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('rgdal', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
install.packages('rgeos', repos='https://cran.uni-muenster.de/', lib = "/usr/lib/R/library")
#install.packages('rstac', repos='https://cran.uni-muenster.de/')
#install.packages('gdalcubes', repos='https://cran.uni-muenster.de/')
#install.packages('raster', repos='https://cran.uni-muenster.de/')

# library.path <- .libPaths()

fileConn<-file("output.txt")
writeLines(.libPaths(), fileConn)
close(fileConn)

# library(sf, lib.loc = library.path)
# library(rgeos, lib.loc = library.path)
# library(rgdal, lib.loc = library.path)
# library(rstac, lib.loc = library.path)
# library(gdalcubes, lib.loc = library.path)
# library(raster, lib.loc = library.path)
